### ISSUE TITLE
Full README not rendering in browser 

### ISSUE THREAD

**Issue by jedsundwall** [OSGeo/PROJ-data#7] opened 2020-01-29 12:32 UTC
If I click to read the full README, GitHub only renders the following text:

` ../README.DATA`

**Comment by rouault** [comment] 2020-01-29 12:38
Can you explain more what you do ? The intent if the the README.DATA is displayed as Markdown if you just go to the home page at https://github.com/OSGeo/PROJ-data

**Comment by jedsundwall** [comment] 2020-01-29 13:30
It appears that the issue may be limited to mobile browsers. Here are screenshots from iOS, which displays a truncated version of the README at https://github.com/OSGeo/PROJ-data. If I click 'Read all of README.md', I see the page in the second screenshot. Perhaps this would be solved by changing the README.DATA file to README.MD?
 
![IMG_0594](https://user-images.githubusercontent.com/110435/73360641-b01cc780-42a3-11ea-8ed1-c3e39ae36264.png)

![IMG_0593](https://user-images.githubusercontent.com/110435/73360634-ac894080-42a3-11ea-849c-4015d58bfb9b.png)

**Comment by nyalldawson** [comment] 2020-06-23 23:10
This is no longer an issue - it must have been fixed by a GitHub update.

**Comment by kbevers** [comment] 2020-06-24 06:01
I can't reproduce either, closing as fixed by the nice people at Github.

**Closed by kbevers** 2020-06-24 06:01 UTC
